### ISSUE TITLE
No results until 90% of the entreprise name is input

### ISSUE THREAD

**Issue by laem** [sgmap/sirene_as_api_front#51]
"octo" -> lots of results :+1: 
"octo t" to "octo technolo" -> No results :-1: 
"octo technolog" and "octo technology" -> 1 good result :+1:

**Comment by Samuelfaure** [comment]
This is due to the way spellchecking works with sunspot/solr when more than one word are inputed. The spellchecking is made on both words separately who are then joined back together. This is made worse by the fact that our spellchecking dictionary is made with indexed values, which very often contains weird typos.

Example : input of 'secretariat gener' will be spellchecked to "secretaria general" instead of "secretariat general" and will yield no result.
This needs to be fixed in the API backend. Im opening a new issue there. Thanks for your feedback.
